feat(LINGUIST-409): Implemented UserGems component, fixed broken color in colors.ts.
LinguistAI/mobile pull request #87
Opened 2024-04-30 17:05 UTC by can-aslan

# You can use this component with just `<UserGems />`

![image](https://github.com/LinguistAI/mobile/assets/86242974/3803580c-c432-42f6-a878-7cb64bb656dc)

2024-05-01 08:37 UTC, selimcanglr commented on components/transaction/UserGems.tsx
> +
Please add `isLoading` here so it won't display the error below if loading takes more time than we think.

2024-05-01 08:38 UTC, selimcanglr submitted a review, later dismissed
Let's add an `ActivityIndicator` while loading the gems.

2024-05-01 09:10 UTC, KardelenCeren commented
It looks great, but it would be better if the component showed whatever number it was given instead of fetching the user's gems itself - so that we can also use the component to show a store item's price.

2024-05-01 10:55 UTC, selimcanglr commented
> It looks great, but it would be better if the component showed whatever number it was given instead of fetching the user's gems itself - so that we can also use the component to show a store item's price.

Yes, maybe you can extract the logic of fetching the data to `UserGemsContainer` and the display logic would remain in `UserGems` but it would receive the data as a prop.

2024-05-03 14:44 UTC, can-aslan commented
![image](https://github.com/LinguistAI/mobile/assets/86242974/4f11b375-12d5-4466-aaf8-0bf864a8e1b6)
### Clickable (ActionButton) User Gems (at the top)
### Static User Gems (at the bottom)

2024-05-03 19:58 UTC, selimcanglr requested changes

2024-05-03 19:58 UTC, selimcanglr commented on components/transaction/GemsIndicatorButton.tsx
> +  handleOpenModal: () => void;
It would be better to name this `onClick`

2024-05-03 19:58 UTC, selimcanglr commented on components/transaction/UserGemsButton.tsx
> +    marginLeft: 120,
You can use:
display: flex,
width: 100%,
justify-content: center,
align-items: center,

2024-05-05 14:45 UTC, selimcanglr commented on components/transaction/UserGems.tsx
> -      <View style={styles.root}>
That's a bit weird, but fair enough

2024-05-05 14:45 UTC, selimcanglr approved these changes

2024-05-05 14:48 UTC, merged