feat(LINGUIST-483): Added placeholders to friend profile
LinguistAI/mobile pull request #92
Opened 2024-05-02 18:52 UTC by KardelenCeren

Added shimmering placeholders and loading indicators to friend profile. 
I also made some minor style changes to friends and friend requests screen, I hope it looks good on every screen

2024-05-03 14:50 UTC, can-aslan requested changes
Could you please attach the screenshot of the changed view? Thanks

2024-05-03 19:47 UTC, selimcanglr approved these changes

2024-05-06 15:38 UTC, can-aslan commented
I can't see the difference when I put the screens side by side, the only change I can see is in friend requests screen where the margin between received and sent is increased. Was this the only change?

2024-05-06 15:48 UTC, KardelenCeren commented
> I can't see the difference when I put the screens side by side, the only change I can see is in friend requests screen where the margin between received and sent is increased. Was this the only change?

I did not change the margin between received and sent - the only change I made was the left and right margins. This was the original on Android: 
![image](https://github.com/LinguistAI/mobile/assets/79415154/105dc8fc-b54b-48ae-9da8-4e3b06a9425c)

2024-05-07 17:37 UTC, merged